In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/kanchana1990/vehicle-dataset-2024/vehicles_dataset.csv

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

**PREPROCESSING**

In [3]:
df = pd.read_csv('/kaggle/input/datasets/kanchana1990/vehicle-dataset-2024/vehicles_dataset.csv')

In [4]:
df.head()

,name,description,make,model,type,year,price,engine,cylinders,fuel,mileage,transmission,trim,body,doors,exterior_color,interior_color,drivetrain
0,2024 Jeep Wagoneer Series II,"\n \n Heated Leather Seats, Nav Sy...",Jeep,Wagoneer,New,2024,74600.0,24V GDI DOHC Twin Turbo,6.0,Gasoline,10.0,8-Speed Automatic,Series II,SUV,4.0,White,Global Black,Four-wheel Drive
1,2024 Jeep Grand Cherokee Laredo,Al West is committed to offering every custome...,Jeep,Grand Cherokee,New,2024,50170.0,OHV,6.0,Gasoline,1.0,8-Speed Automatic,Laredo,SUV,4.0,Metallic,Global Black,Four-wheel Drive
2,2024 GMC Yukon XL Denali,NaN,GMC,Yukon XL,New,2024,96410.0,"6.2L V-8 gasoline direct injection, variable v...",8.0,Gasoline,0.0,Automatic,Denali,SUV,4.0,Summit White,Teak/Light Shale,Four-wheel Drive
3,2023 Dodge Durango Pursuit,White Knuckle Clearcoat 2023 Dodge Durango Pur...,Dodge,Durango,New,2023,46835.0,16V MPFI OHV,8.0,Gasoline,32.0,8-Speed Automatic,Pursuit,SUV,4.0,White Knuckle Clearcoat,Black,All-wheel Drive
4,2024 RAM 3500 Laramie,\n \n 2024 Ram 3500 Laramie Billet...,RAM,3500,New,2024,81663.0,24V DDI OHV Turbo Diesel,6.0,Diesel,10.0,6-Speed Automatic,Laramie,Pickup Truck,4.0,Silver,Black,Four-wheel Drive

In [5]:
df.shape

(1002, 18)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1002 entries, 0 to 1001
Data columns (total 18 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   name            1002 non-null   object
 1   description     946 non-null    object
 2   make            1002 non-null   object
 3   model           1002 non-null   object
 4   type            1002 non-null   object
 5   year            1002 non-null   int64
 6   price           979 non-null    float64
 7   engine          1000 non-null   object
 8   cylinders       897 non-null    float64
 9   fuel            995 non-null    object
 10  mileage         968 non-null    float64
 11  transmission    1000 non-null   object
 12  trim            1001 non-null   object
 13  body            999 non-null    object
 14  doors           995 non-null    float64
 15  exterior_color  997 non-null    object
 16  interior_color  964 non-null    object
 17  drivetrain      1002 non-null   object
dtypes: float64(4), int64(1), object(13)
memory usage: 141.0+ KB

In [7]:
df.isnull().sum()

name                0
description        56
make                0
model               0
type                0
year                0
price              23
engine              2
cylinders         105
fuel                7
mileage            34
transmission        2
trim                1
body                3
doors               7
exterior_color      5
interior_color     38
drivetrain          0
dtype: int64

In [8]:
df = df.dropna(subset = ['price'])

In [9]:
df['price'].isnull().sum()

np.int64(0)

In [10]:
df.isnull().sum()

name                0
description        56
make                0
model               0
type                0
year                0
price               0
engine              2
cylinders         102
fuel                7
mileage            34
transmission        2
trim                1
body                3
doors               7
exterior_color      5
interior_color     37
drivetrain          0
dtype: int64

In [11]:
df = df.drop(columns=['description'])

In [12]:
df.head()

,name,make,model,type,year,price,engine,cylinders,fuel,mileage,transmission,trim,body,doors,exterior_color,interior_color,drivetrain
0,2024 Jeep Wagoneer Series II,Jeep,Wagoneer,New,2024,74600.0,24V GDI DOHC Twin Turbo,6.0,Gasoline,10.0,8-Speed Automatic,Series II,SUV,4.0,White,Global Black,Four-wheel Drive
1,2024 Jeep Grand Cherokee Laredo,Jeep,Grand Cherokee,New,2024,50170.0,OHV,6.0,Gasoline,1.0,8-Speed Automatic,Laredo,SUV,4.0,Metallic,Global Black,Four-wheel Drive
2,2024 GMC Yukon XL Denali,GMC,Yukon XL,New,2024,96410.0,"6.2L V-8 gasoline direct injection, variable v...",8.0,Gasoline,0.0,Automatic,Denali,SUV,4.0,Summit White,Teak/Light Shale,Four-wheel Drive
3,2023 Dodge Durango Pursuit,Dodge,Durango,New,2023,46835.0,16V MPFI OHV,8.0,Gasoline,32.0,8-Speed Automatic,Pursuit,SUV,4.0,White Knuckle Clearcoat,Black,All-wheel Drive
4,2024 RAM 3500 Laramie,RAM,3500,New,2024,81663.0,24V DDI OHV Turbo Diesel,6.0,Diesel,10.0,6-Speed Automatic,Laramie,Pickup Truck,4.0,Silver,Black,Four-wheel Drive

In [13]:
df['mileage'] = df['mileage'].fillna(df['mileage'].mean())

In [14]:
df['cylinders'] = df['cylinders'].fillna(df['cylinders'].mode()[0])

In [15]:
df.isnull().sum()

name               0
make               0
model              0
type               0
year               0
price              0
engine             2
cylinders          0
fuel               7
mileage            0
transmission       2
trim               1
body               3
doors              7
exterior_color     5
interior_color    37
drivetrain         0
dtype: int64

In [16]:
categorical_cols = [
    'engine',
    'fuel',
    'transmission',
    'trim',
    'body',
    'doors',
    'exterior_color',
    'interior_color'
]

for col in categorical_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

In [17]:
df.isnull().sum()

name              0
make              0
model             0
type              0
year              0
price             0
engine            0
cylinders         0
fuel              0
mileage           0
transmission      0
trim              0
body              0
doors             0
exterior_color    0
interior_color    0
drivetrain        0
dtype: int64

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 979 entries, 0 to 1001
Data columns (total 17 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   name            979 non-null    object
 1   make            979 non-null    object
 2   model           979 non-null    object
 3   type            979 non-null    object
 4   year            979 non-null    int64
 5   price           979 non-null    float64
 6   engine          979 non-null    object
 7   cylinders       979 non-null    float64
 8   fuel            979 non-null    object
 9   mileage         979 non-null    float64
 10  transmission    979 non-null    object
 11  trim            979 non-null    object
 12  body            979 non-null    object
 13  doors           979 non-null    float64
 14  exterior_color  979 non-null    object
 15  interior_color  979 non-null    object
 16  drivetrain      979 non-null    object
dtypes: float64(4), int64(1), object(12)
memory usage: 137.7+ KB

In [19]:
def simplify_transmission(x):

    x = str(x).lower()

    if 'automatic' in x or 'a/t' in x:
        return 'Automatic'

    elif 'manual' in x:
        return 'Manual'

    elif 'cvt' in x:
        return 'CVT'

    else:
        return 'Other'

df['transmission'] = df['transmission'].apply(simplify_transmission)

**ENCODING**

In [20]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

label_encoding_col = [
    'name',
    'model',
    'engine',
    'trim',
    'exterior_color',
    'interior_color'
]

for col in label_encoding_col:
    df[col] = le.fit_transform(df[col])

df = pd.get_dummies(df, columns=[
 'fuel',
 'transmission',
 'body',
 'drivetrain',
 'type',
 'make'
])

In [21]:
print(df.columns)

Index(['name', 'model', 'year', 'price', 'engine', 'cylinders', 'mileage',
       'trim', 'doors', 'exterior_color', 'interior_color', 'fuel_Diesel',
       'fuel_Diesel (B20 capable)', 'fuel_E85 Flex Fuel', 'fuel_Electric',
       'fuel_Gasoline', 'fuel_Hybrid', 'fuel_PHEV Hybrid Fuel',
       'transmission_Automatic', 'transmission_CVT', 'transmission_Other',
       'body_Cargo Van', 'body_Convertible', 'body_Hatchback', 'body_Minivan',
       'body_Passenger Van', 'body_Pickup Truck', 'body_SUV', 'body_Sedan',
       'drivetrain_All-wheel Drive', 'drivetrain_Four-wheel Drive',
       'drivetrain_Front-wheel Drive', 'drivetrain_Rear-wheel Drive',
       'type_New', 'make_Acura', 'make_Audi', 'make_BMW', 'make_Buick',
       'make_Cadillac', 'make_Chevrolet', 'make_Chrysler', 'make_Dodge',
       'make_Ford', 'make_GMC', 'make_Genesis', 'make_Honda', 'make_Hyundai',
       'make_INFINITI', 'make_Jaguar', 'make_Jeep', 'make_Kia',
       'make_Land Rover', 'make_Lexus', 'make_Lincoln', 'make_Mazda',
       'make_Mercedes-Benz', 'make_Nissan', 'make_RAM', 'make_Subaru',
       'make_Toyota', 'make_Volkswagen', 'make_Volvo'],
      dtype='object')

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 979 entries, 0 to 1001
Data columns (total 62 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   name                          979 non-null    int64
 1   model                         979 non-null    int64
 2   year                          979 non-null    int64
 3   price                         979 non-null    float64
 4   engine                        979 non-null    int64
 5   cylinders                     979 non-null    float64
 6   mileage                       979 non-null    float64
 7   trim                          979 non-null    int64
 8   doors                         979 non-null    float64
 9   exterior_color                979 non-null    int64
 10  interior_color                979 non-null    int64
 11  fuel_Diesel                   979 non-null    bool
 12  fuel_Diesel (B20 capable)     979 non-null    bool
 13  fuel_E85 Flex Fuel            979 non-null    bool
 14  fuel_Electric                 979 non-null    bool
 15  fuel_Gasoline                 979 non-null    bool
 16  fuel_Hybrid                   979 non-null    bool
 17  fuel_PHEV Hybrid Fuel         979 non-null    bool
 18  transmission_Automatic        979 non-null    bool
 19  transmission_CVT              979 non-null    bool
 20  transmission_Other            979 non-null    bool
 21  body_Cargo Van                979 non-null    bool
 22  body_Convertible              979 non-null    bool
 23  body_Hatchback                979 non-null    bool
 24  body_Minivan                  979 non-null    bool
 25  body_Passenger Van            979 non-null    bool
 26  body_Pickup Truck             979 non-null    bool
 27  body_SUV                      979 non-null    bool
 28  body_Sedan                    979 non-null    bool
 29  drivetrain_All-wheel Drive    979 non-null    bool
 30  drivetrain_Four-wheel Drive   979 non-null    bool
 31  drivetrain_Front-wheel Drive  979 non-null    bool
 32  drivetrain_Rear-wheel Drive   979 non-null    bool
 33  type_New                      979 non-null    bool
 34  make_Acura                    979 non-null    bool
 35  make_Audi                     979 non-null    bool
 36  make_BMW                      979 non-null    bool
 37  make_Buick                    979 non-null    bool
 38  make_Cadillac                 979 non-null    bool
 39  make_Chevrolet                979 non-null    bool
 40  make_Chrysler                 979 non-null    bool
 41  make_Dodge                    979 non-null    bool
 42  make_Ford                     979 non-null    bool
 43  make_GMC                      979 non-null    bool
 44  make_Genesis                  979 non-null    bool
 45  make_Honda                    979 non-null    bool
 46  make_Hyundai                  979 non-null    bool
 47  make_INFINITI                 979 non-null    bool
 48  make_Jaguar                   979 non-null    bool
 49  make_Jeep                     979 non-null    bool
 50  make_Kia                      979 non-null    bool
 51  make_Land Rover               979 non-null    bool
 52  make_Lexus                    979 non-null    bool
 53  make_Lincoln                  979 non-null    bool
 54  make_Mazda                    979 non-null    bool
 55  make_Mercedes-Benz            979 non-null    bool
 56  make_Nissan                   979 non-null    bool
 57  make_RAM                      979 non-null    bool
 58  make_Subaru                   979 non-null    bool
 59  make_Toyota                   979 non-null    bool
 60  make_Volkswagen               979 non-null    bool
 61  make_Volvo                    979 non-null    bool
dtypes: bool(51), float64(4), int64(7)
memory usage: 140.5 KB

In [23]:
print(df.select_dtypes(include='object').columns)

Index([], dtype='object')

**DATA SPLIT**

In [24]:
X = df.drop('price', axis=1)
y = df['price']

In [25]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)

**LINEAR REGRESSION**

In [26]:
from sklearn.linear_model import LinearRegression
LR_model = LinearRegression()
LR_model.fit(X_train, y_train)

LinearRegression()

In [27]:
y_pred = LR_model.predict(X_test)

In [28]:
from sklearn.metrics import mean_absolute_error, r2_score,mean_squared_error

mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)

print("MAE:", mae)
print("RMSE:", rmse)
print("R2 Score:", r2)

MAE: 7369.342119970606
RMSE: 9181.461063513338
R2 Score: 0.7239623976748468

**Decision Tree**

In [29]:
from sklearn.tree import DecisionTreeRegressor
dt = DecisionTreeRegressor(
    random_state=42
)
dt.fit(X_train, y_train)

DecisionTreeRegressor(random_state=42)

In [30]:
y_pred_dt = dt.predict(X_test)

In [31]:
from sklearn.metrics import mean_absolute_error, r2_score,mean_squared_error

mae = mean_absolute_error(y_test, y_pred_dt)
rmse = np.sqrt(mean_squared_error(y_test, y_pred_dt))
r2 = r2_score(y_test, y_pred_dt)

print("MAE:", mae)
print("RMSE:", rmse)
print("R2 Score:", r2)

MAE: 6121.376360544217
RMSE: 12369.482938376801
R2 Score: 0.4989884422963131

In [32]:
print("Train R2:", dt.score(X_train, y_train))
print("Test R2 :", dt.score(X_test, y_test))

Train R2: 0.9994454142854805
Test R2 : 0.4989884422963131

**Decision Tree Updated**

In [33]:
from sklearn.tree import DecisionTreeRegressor
dt_updated = DecisionTreeRegressor(
    max_depth=10,
    min_samples_split=10,
    min_samples_leaf=5,
    random_state=42
)
dt_updated.fit(X_train, y_train)

DecisionTreeRegressor(max_depth=10, min_samples_leaf=5, min_samples_split=10,
                      random_state=42)

In [34]:
y_pred_dt_updated = dt_updated.predict(X_test)

In [35]:
from sklearn.metrics import mean_absolute_error, r2_score,mean_squared_error

mae = mean_absolute_error(y_test, y_pred_dt_updated)
rmse = np.sqrt(mean_squared_error(y_test, y_pred_dt_updated))
r2 = r2_score(y_test, y_pred_dt_updated)

print("MAE:", mae)
print("RMSE:", rmse)
print("R2 Score:", r2)

MAE: 5894.427560600927
RMSE: 8949.946028549877
R2 Score: 0.7377077337166278

In [36]:
print("Train R2:", dt_updated.score(X_train, y_train))
print("Test R2 :", dt_updated.score(X_test, y_test))

Train R2: 0.8632356535370544
Test R2 : 0.7377077337166278

**Random Forest**

In [37]:
from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor(
    n_estimators=100,
    max_depth=10,
    min_samples_split=10,
    min_samples_leaf=5,
    random_state=42,
    n_jobs=-1
)

rf.fit(X_train, y_train)

RandomForestRegressor(max_depth=10, min_samples_leaf=5, min_samples_split=10,
                      n_jobs=-1, random_state=42)

In [38]:
y_pred_rf = rf.predict(X_test)

In [39]:
from sklearn.metrics import mean_absolute_error, r2_score,mean_squared_error

mae = mean_absolute_error(y_test, y_pred_rf)
rmse = np.sqrt(mean_squared_error(y_test, y_pred_rf))
r2 = r2_score(y_test, y_pred_rf)

print("MAE:", mae)
print("RMSE:", rmse)
print("R2 Score:", r2)

MAE: 6026.530132944794
RMSE: 9255.653923527614
R2 Score: 0.7194832051487103

In [40]:
print("Train R2:", rf.score(X_train, y_train))
print("Test R2 :", rf.score(X_test, y_test))

Train R2: 0.8392056854275005
Test R2 : 0.7194832051487103

**Random Forest updated**

In [41]:
from sklearn.ensemble import RandomForestRegressor

rf_new = RandomForestRegressor(
    n_estimators=300,
    random_state=42,
    n_jobs=-1
)

rf_new.fit(X_train, y_train)

RandomForestRegressor(n_estimators=300, n_jobs=-1, random_state=42)

In [42]:
y_pred_rf_new = rf_new.predict(X_test)

In [43]:
from sklearn.metrics import mean_absolute_error, r2_score,mean_squared_error

mae = mean_absolute_error(y_test, y_pred_rf_new)
rmse = np.sqrt(mean_squared_error(y_test, y_pred_rf_new))
r2 = r2_score(y_test, y_pred_rf_new)

print("MAE:", mae)
print("RMSE:", rmse)
print("R2 Score:", r2)

MAE: 5010.127378468847
RMSE: 8464.939416620491
R2 Score: 0.7653652345450829

In [44]:
print("Train R2:", rf_new.score(X_train, y_train))
print("Test R2 :", rf_new.score(X_test, y_test))

Train R2: 0.9723705876177096
Test R2 : 0.7653652345450829

In [45]:
from sklearn.ensemble import GradientBoostingRegressor

gbr = GradientBoostingRegressor(n_estimators=200,learning_rate=0.05,max_depth=4,random_state=42)

gbr.fit(X_train, y_train)

GradientBoostingRegressor(learning_rate=0.05, max_depth=4, n_estimators=200,
                          random_state=42)

In [46]:
y_pred_gbr = gbr.predict(X_test)

In [47]:
from sklearn.metrics import (mean_absolute_error,mean_squared_error,r2_score)

import numpy as np

mae = mean_absolute_error(y_test, y_pred_gbr)
rmse = np.sqrt(mean_squared_error(y_test, y_pred_gbr))
r2 = r2_score(y_test, y_pred_gbr)

print("MAE:", mae)
print("RMSE:", rmse)
print("R2 Score:", r2)

MAE: 5402.127060962747
RMSE: 8620.80381461413
R2 Score: 0.7566450544436679

In [49]:
importance = pd.DataFrame({
    "Feature": X.columns,
    "Importance": rf_new.feature_importances_
}).sort_values(
    by="Importance",
    ascending=False
)

print(importance.head(15))

                         Feature  Importance
4                      cylinders    0.167154
0                           name    0.146218
1                          model    0.143385
14                 fuel_Gasoline    0.115865
6                           trim    0.056792
54            make_Mercedes-Benz    0.042478
3                         engine    0.037666
5                        mileage    0.032300
34                     make_Audi    0.026591
13                 fuel_Electric    0.026329
30  drivetrain_Front-wheel Drive    0.022843
8                 exterior_color    0.020044
41                     make_Ford    0.017806
9                 interior_color    0.015185
10                   fuel_Diesel    0.013346

**Random Forest New without name**

In [51]:
X2 = df.drop('name', axis=1)

In [56]:
X2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 979 entries, 0 to 1001
Data columns (total 61 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   model                         979 non-null    int64
 1   year                          979 non-null    int64
 2   price                         979 non-null    float64
 3   engine                        979 non-null    int64
 4   cylinders                     979 non-null    float64
 5   mileage                       979 non-null    float64
 6   trim                          979 non-null    int64
 7   doors                         979 non-null    float64
 8   exterior_color                979 non-null    int64
 9   interior_color                979 non-null    int64
 10  fuel_Diesel                   979 non-null    bool
 11  fuel_Diesel (B20 capable)     979 non-null    bool
 12  fuel_E85 Flex Fuel            979 non-null    bool
 13  fuel_Electric                 979 non-null    bool
 14  fuel_Gasoline                 979 non-null    bool
 15  fuel_Hybrid                   979 non-null    bool
 16  fuel_PHEV Hybrid Fuel         979 non-null    bool
 17  transmission_Automatic        979 non-null    bool
 18  transmission_CVT              979 non-null    bool
 19  transmission_Other            979 non-null    bool
 20  body_Cargo Van                979 non-null    bool
 21  body_Convertible              979 non-null    bool
 22  body_Hatchback                979 non-null    bool
 23  body_Minivan                  979 non-null    bool
 24  body_Passenger Van            979 non-null    bool
 25  body_Pickup Truck             979 non-null    bool
 26  body_SUV                      979 non-null    bool
 27  body_Sedan                    979 non-null    bool
 28  drivetrain_All-wheel Drive    979 non-null    bool
 29  drivetrain_Four-wheel Drive   979 non-null    bool
 30  drivetrain_Front-wheel Drive  979 non-null    bool
 31  drivetrain_Rear-wheel Drive   979 non-null    bool
 32  type_New                      979 non-null    bool
 33  make_Acura                    979 non-null    bool
 34  make_Audi                     979 non-null    bool
 35  make_BMW                      979 non-null    bool
 36  make_Buick                    979 non-null    bool
 37  make_Cadillac                 979 non-null    bool
 38  make_Chevrolet                979 non-null    bool
 39  make_Chrysler                 979 non-null    bool
 40  make_Dodge                    979 non-null    bool
 41  make_Ford                     979 non-null    bool
 42  make_GMC                      979 non-null    bool
 43  make_Genesis                  979 non-null    bool
 44  make_Honda                    979 non-null    bool
 45  make_Hyundai                  979 non-null    bool
 46  make_INFINITI                 979 non-null    bool
 47  make_Jaguar                   979 non-null    bool
 48  make_Jeep                     979 non-null    bool
 49  make_Kia                      979 non-null    bool
 50  make_Land Rover               979 non-null    bool
 51  make_Lexus                    979 non-null    bool
 52  make_Lincoln                  979 non-null    bool
 53  make_Mazda                    979 non-null    bool
 54  make_Mercedes-Benz            979 non-null    bool
 55  make_Nissan                   979 non-null    bool
 56  make_RAM                      979 non-null    bool
 57  make_Subaru                   979 non-null    bool
 58  make_Toyota                   979 non-null    bool
 59  make_Volkswagen               979 non-null    bool
 60  make_Volvo                    979 non-null    bool
dtypes: bool(51), float64(4), int64(6)
memory usage: 132.9 KB

In [59]:
X_X2 = X2.drop('price', axis=1)
y_X2 = X2['price']

In [60]:
from sklearn.model_selection import train_test_split

X_train_X2, X_test_X2, y_train_X2, y_test_X2 = train_test_split(X_X2,y_X2,test_size=0.2,random_state=42)

In [61]:
from sklearn.ensemble import RandomForestRegressor

rf_new = RandomForestRegressor(
    n_estimators=300,
    random_state=42,
    n_jobs=-1
)

rf_new.fit(X_train_X2, y_train_X2)

RandomForestRegressor(n_estimators=300, n_jobs=-1, random_state=42)

In [63]:
y_pred_rf_new_X2 = rf_new.predict(X_test_X2)

In [65]:
mae = mean_absolute_error(y_test_X2, y_pred_rf_new_X2)

rmse = np.sqrt(
    mean_squared_error(y_test_X2, y_pred_rf_new_X2)
)

r2 = r2_score(
    y_test_X2,
    y_pred_rf_new_X2
)

print("MAE:", mae)
print("RMSE:", rmse)
print("R2 Score:", r2)

MAE: 4973.466959704552
RMSE: 8580.852297249488
R2 Score: 0.7588953947165594

**Random Forest New (Without 'name','model', 'trim')**

In [67]:
X3 = df.drop(['name','model', 'trim'], axis=1)

In [69]:
X_X3 = X3.drop('price', axis=1)
y_X3 = X3['price']

In [70]:
from sklearn.model_selection import train_test_split

X_train_X3, X_test_X3, y_train_X3, y_test_X3 = train_test_split(X_X3,y_X3,test_size=0.2,random_state=42)

In [71]:
from sklearn.ensemble import RandomForestRegressor

rf_new = RandomForestRegressor(
    n_estimators=300,
    random_state=42,
    n_jobs=-1
)

rf_new.fit(X_train_X3, y_train_X3)

RandomForestRegressor(n_estimators=300, n_jobs=-1, random_state=42)

In [72]:
y_pred_rf_new_X3 = rf_new.predict(X_test_X3)

In [73]:
mae = mean_absolute_error(y_test_X2, y_pred_rf_new_X3)

rmse = np.sqrt(
    mean_squared_error(y_test_X2, y_pred_rf_new_X3)
)

r2 = r2_score(
    y_test_X3,
    y_pred_rf_new_X3
)

print("MAE:", mae)
print("RMSE:", rmse)
print("R2 Score:", r2)

MAE: 5418.445968356426
RMSE: 8018.303045062746
R2 Score: 0.7894721356615639

In [76]:
print("Train R2:", rf_new.score(X_train_X3, y_train_X3))
print("Test R2 :", rf_new.score(X_test_X3, y_test_X3))

Train R2: 0.9679993810184416
Test R2 : 0.7894721356615639

**XGBoost WITHOUT 'name','model', 'trim'**

In [77]:
import xgboost
from xgboost import XGBRegressor

xgb = XGBRegressor(
    n_estimators=300,
    max_depth=6,
    learning_rate=0.05,
    random_state=42
)

xgb.fit(X_train_X3, y_train_X3)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.05, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=6,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=300,
             n_jobs=None, num_parallel_tree=None, ...)

In [78]:
y_pred_xgb = xgb.predict(X_test_X3)

In [79]:
from sklearn.metrics import (mean_absolute_error,mean_squared_error,r2_score)

import numpy as np

mae = mean_absolute_error(y_test_X3, y_pred_xgb)

rmse = np.sqrt(mean_squared_error(y_test_X3, y_pred_xgb))

r2 = r2_score(y_test_X3,y_pred_xgb)

print("MAE:", mae)
print("RMSE:", rmse)
print("R2 Score:", r2)

MAE: 5476.506995376276
RMSE: 8238.00876250205
R2 Score: 0.7777769254480452

In [80]:
print("Train R2:", xgb.score(X_train_X3, y_train_X3))
print("Test R2 :", xgb.score(X_test_X3, y_test_X3))

Train R2: 0.9657145331889878
Test R2 : 0.7777769254480452